apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: backstage
type: Opaque
data:
  POSTGRES_USER: YmFja3N0YWdl #backstage
  POSTGRES_PASSWORD: YmFja3N0YWdl
  POSTGRES_HOST: cG9zdGdyZXM= #postgres
  POSTGRES_PORT: NTQzMg== #5432
